version: '3.8'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx2
    ports:
      - 8001:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - postgres
    #extra_hosts:
      #- "host.docker.internal:172.18.7.73"
      #- "host.docker.internal:192.168.0.75"
    networks:
      - networkapp

  postgres:
    image: postgres:13
    container_name: postgres-ocp
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: seatsa_ocp
      POSTGRES_USER: seatsa_user
      POSTGRES_PASSWORD: temporal
    ports:
      - "5433:5432"
    networks:
        - networkapp

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ocp
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adriano_alanis@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: temporal
    depends_on:
      - postgres
    networks:
      - networkapp
  mysql:
    image: mariadb:10.9.8
    container_name: mysql-ocp
    restart: always
    environment:
      MYSQL_DATABASE: 'seatsa_ocp'
      MYSQL_USER: 'seatsa_user'
      MYSQL_PASSWORD: 'temporal'
      MYSQL_ROOT_PASSWORD: 'temporal'
    ports:
      - 3069:3306
    volumes:
      - dbocp:/var/lib/mysql
    networks:
      - networkapp
  phpmyadmin:
    image: phpmyadmin:5.1.1
    container_name: phpmyadmin-ocp
    ports:
        - 8080:80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 512M
    restart: unless-stopped
    networks:
      - networkapp
    depends_on:
      - mysql
  php:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    image: php:7.4-apache
    container_name: php-ocp
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    networks:
      - networkapp

networks:
  networkapp:
    #driver: bridge

volumes:
  dbocp:
  postgres_data:
    
